### PR TITLE
Forward 5.x branch into master

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@davidbrochart this gives a good idea of what ought to be forward ported to master.

**Comment by SylvainCorlay** [comment]
@minrk do you remember why releases were made in the 5.x branch in the beginning.

**Comment by davidbrochart** [comment]
I just removed the "release" commits.

**Comment by MSeal** [comment]
I left a comment in #511 but I think so long as i e of us tests against nbclient, papermill, and notebook servers and does a thorough read of the changes in master but not in 5.x I think we can merge. For the  6.0release we may also want to do python 3.5+ only change like all the other jupyter libraries are doing too

**Comment by davidbrochart** [comment]
I tested `nbclient` with this PR, all tests pass: https://github.com/jupyter/nbclient/pull/25

**Comment by minrk** [comment]
@SylvainCorlay It's 6.x for the new kernel discovery machinery (#261), which is still in draft, I think.

**Comment by davidbrochart** [comment]
I tested `papermill` with this PR, all tests pass: https://github.com/nteract/papermill/pull/475

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay It's 6.x for the new kernel discovery machinery (#261), which is still in draft, I think.

@minrk @mseal @davidbrochart @maartenbreddels since this this is still in draft after more than two years, I propose that we

 - rename `5.x` into `master`.
 - call the current master branch including this PR "kernel discovery"
 - backport all PRs that are only in the current master in 5.x

That will make things clearer for future releases in my opinion.

Thoughts?

**Comment by MSeal** [comment]
@SylvainCorlay I'm fine with that plan, it'll be lower risk as well.

**Comment by minrk** [comment]
I'm okay with that. I think the kernel discovery plan has moved toward the new jupyter-protocol and friends packages anyway, rather than trying to do it in-place in jupyter-client.

**Comment by davidbrochart** [comment]
I have a PR for back-porting `master` to `5.x` (excluding the kernel discovery commits): https://github.com/jupyter/jupyter_client/pull/516

**Comment by SylvainCorlay** [comment]
Closing as we are swapping master with 5.x

**Pull request closed without merging**
