### PR TITLE
Drop Travis CI, add GitHub Actions

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
[In my branch](https://github.com/davidbrochart/jupyter_client/tree/gha) I can see two failures on macos with python [3.8](https://github.com/davidbrochart/jupyter_client/runs/1363631301) and [3.9](https://github.com/davidbrochart/jupyter_client/runs/1363631321):
```
../../../hostedtoolcache/Python/3.8.6/x64/lib/python3.8/multiprocessing/popen_spawn_posix.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

obj = <Process name='Process-4' parent=4583 initial>
file = <_io.BytesIO object at 0x11276ea40>, protocol = None

    def dump(obj, file, protocol=None):
        '''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'

../../../hostedtoolcache/Python/3.8.6/x64/lib/python3.8/multiprocessing/reduction.py:60: AttributeError
```
I will just exclude these ones for now.

**Comment by davidbrochart** [comment]
Also, the windows test never start, so I removed windows testing.

**Comment by davidbrochart** [comment]
Works fine now. I guess this is fine, since we're already testing more environments than previously with Travis CI.
BTW, I dropped python 3.5.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Pull request merged**
