### PR TITLE
Fix qtconsole issues

### PR DESCRIPTION
**Pull request by davidbrochart**
@ccordoba12 this should fix the issues you were having with v6.1.13 in spyder. I checked that qtconsole works fine, but it might be worth trying spyder too. Actually I should open PRs in upstream projects with this jupyter_client.

### CODE REVIEW

**Comment by davidbrochart** [comment]
I've been opening PRs in [Voila](https://github.com/voila-dashboards/voila/pull/868), [nbconvert](https://github.com/jupyter/nbconvert/pull/1545) and [qtconsole](https://github.com/jupyter/qtconsole/pull/477), and this seems to be going well. I'm going to merge this PR and make a release, if there is no objection.

**Comment by ccordoba12** [comment]
Hey @davidbrochart, thanks a lot for your prompt help! Could you give me a couple of hours before merging? I'd like to run Spyder's test suite against this too, just to be sure things are ok on our side.

**Comment by davidbrochart** [comment]
Sure, take your time, it's night time over here so not planning to do it until tomorrow.

**Comment by davidbrochart** [comment]
@ccordoba12 I tried spyder and fixed another issue. Could you please confirm everything works fine on your side?

**Comment by ccordoba12** [comment]
Sorry for the delay @davidbrochart, I'm running our test suite against this branch here: https://github.com/spyder-ide/spyder/pull/15205.

**Comment by ccordoba12** [comment]
I'm getting this error in some of our console tests:

```python-traceback
ERROR    asyncio:base_events.py:1619 Exception in callback BaseAsyncIOLoop._handle_events(413, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(413, 1)>
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <Context object at 0x7f099c46df00> is already entered
ERROR    asyncio:base_events.py:1619 Exception in callback BaseAsyncIOLoop._handle_events(411, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(411, 1)>
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <Context object at 0x7f099c4ec050> is already entered
ERROR    asyncio:base_events.py:1619 Exception in callback BaseAsyncIOLoop._handle_events(413, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(413, 1)>
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <Context object at 0x7f099c46df00> is already entered
```

Reference: https://github.com/spyder-ide/spyder/pull/15205/checks?check_run_id=2307155447

**Comment by davidbrochart** [comment]
Thanks for reporting @ccordoba12, it seems to be fixed now: https://github.com/spyder-ide/spyder/pull/15217

**Comment by ccordoba12** [comment]
Yep, that seems to be the case. Then I'd say we're ready to merge this one.

Thanks again for your quick response to fix this situation and help us to be compatible with the future jupyte_client. We really appreciate it.

**Comment by stonebig** [comment]
is it normal that jupyter-client-0.6.2 is not published on pypi yet ?

**Comment by SylvainCorlay** [comment]
Yes, it was yanked as it broke downstream packages.

We will be making pre releases towards a 7.0 version.

**Pull request merged**
