### PR TITLE
Secure write for connection file

### PR DESCRIPTION
**Pull request by MSeal**
Includes release information, as we should follow the merge directly with a patch release for 5.3.2.

### CODE REVIEW

**Comment by MSeal** [comment]
I did some python 2 / 3 testing with downstream libraries as well and didn't run into any issues.

**Comment by vidartf** [comment]
It seems the added dependency from this PR did not make it into the conda forge package, https://github.com/jupyterlab/jupyterlab/issues/7259 . I'll create an issue on https://github.com/conda-forge/jupyter_client-feedstock to track this.

**Comment by scivm** [comment]
This has broken jupyterhub on the server?  

See https://stackoverflow.com/questions/58214911/kernel-error-jupyter-client-connect-py-assertionerror

I am running into this issue in jupyterhub.

**Comment by MSeal** [comment]
It might be related to https://github.com/conda-forge/jupyter_client-feedstock/issues/35? The conda recipes are their own bag of abstractions wrapping the source code so it can be difficult to untangle what's a source issue and what's build issue therein. Can you post the `conda list` for the failing instance? It's likely one or more of the jupyter packages are out of date in the conda feed.

**Comment by scivm** [comment]
Here is the output from conda list in the Jupyter project datascience-notebook built December 2, 2019 03:31 PM.  This is running in an Azure AKS cluster with the following storage permissions:

`kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0755
  - file_mode=0600
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS`

I confirmed I get the error:

File "/opt/conda/lib/python3.7/site-packages/jupyter_client/connect.py", line 105, in secure_write
    assert '0600' == oct(stat.S_IMODE(os.stat(fname).st_mode)).replace('0o', '0')
AssertionError

[](https://hub.docker.com/r/jupyter/datascience-notebook)

image: jupyter/datascience-notebook:latest

Also check https://github.com/jupyter/notebook/issues/4937

`jovyan@jupyter-shamberger-20michael-20-28ext-29:~$ conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
alembic                   1.3.1                      py_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.8.1                    py37_0    conda-forge
binutils_impl_linux-64    2.33.1               he1b5a44_7    conda-forge
binutils_linux-64         2.33.1              h9595d00_15    conda-forge
blas                      2.14                   openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     1.3.4                    py37_0    conda-forge
bwidget                   1.9.13                        0    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.14.12              h8948797_3    defaults
certifi                   2019.11.28               py37_0    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
conda                     4.7.12                   py37_0    conda-forge
conda-package-handling    1.6.0            py37h516909a_1    conda-forge
configurable-http-proxy   1.3.0                         0    conda-forge
cryptography              2.8              py37h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.14          py37he1b5a44_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.2.0                      py_0    conda-forge
dask-core                 2.2.0                      py_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
dill                      0.3.1.1                  py37_0    conda-forge
distributed               2.5.2                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
fastcache                 1.1.0            py37h516909a_0    conda-forge
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.10.0               he983fc9_1    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
fsspec                    0.6.1                      py_0    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_2    conda-forge
gcc_linux-64              7.3.0               h553295d_15    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_2    conda-forge
gfortran_linux-64         7.3.0               h553295d_15    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gmpy2                     2.1.0b1          py37h04dde30_0    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.4               h294904e_1006    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_2    conda-forge
gxx_linux-64              7.3.0               h553295d_15    conda-forge
h5py                      2.9.0           nompi_py37h513d04c_1104    conda-forge
harfbuzz                  1.9.0             he243708_1001    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
importlib_metadata        1.1.0                    py37_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.10.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.14.0                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterhub                1.0.0                    py37_0    conda-forge
jupyterlab                1.2.1                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
liblapacke                3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_4    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.9.2                h8b12597_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libtiff                   4.1.0                hc3755c2_1    conda-forge
libuuid                   1.0.3                h1bed415_2    defaults
libuv                     1.33.1               h516909a_0    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
make                      4.2.1             h14c3975_2004    conda-forge
mako                      1.1.0                      py_0    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib-base           3.1.1            py37hfd891ef_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
mpc                       1.1.0             h04dde30_1006    conda-forge
mpfr                      4.0.2                he80fd80_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nodejs                    12.4.0               he1b5a44_0    conda-forge
notebook                  6.0.0                    py37_0    conda-forge
numba                     0.45.1           py37hb3f55d8_0    conda-forge
numexpr                   2.6.9           py37h637b7d7_1000    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
pandoc                    2.8.0.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               h049681c_0    defaults
parso                     0.5.1                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.1            py37hd70f55b_1    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.2                      py_0    conda-forge
protobuf                  3.9.2            py37he1b5a44_1    conda-forge
psutil                    5.6.7            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycosat                   0.6.3           py37h516909a_1002    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pycurl                    7.43.0.3         py37h16ce93b_1    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pyrsistent                0.15.6           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h0371630_0    defaults
python-dateutil           2.8.1                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyyaml                    5.1.2            py37h516909a_1    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
r-askpass                 1.1               r36hcdcec82_1    conda-forge
r-assertthat              0.2.1             r36h6115d3f_1    conda-forge
r-backports               1.1.5             r36hcdcec82_0    conda-forge
r-base                    3.6.1                h9bb98a2_1    defaults
r-base64enc               0.1_3           r36hcdcec82_1003    conda-forge
r-bit                     1.1_14            r36hcdcec82_1    conda-forge
r-bit64                   0.9_7           r36hcdcec82_1001    conda-forge
r-bitops                  1.0_6           r36hcdcec82_1003    conda-forge
r-blob                    1.2.0                     r36_1    conda-forge
r-brew                    1.0_6           r36h6115d3f_1002    conda-forge
r-broom                   0.5.2             r36h6115d3f_1    conda-forge
r-callr                   3.3.2             r36h6115d3f_0    conda-forge
r-caret                   6.0_84            r36hcdcec82_1    conda-forge
r-cellranger              1.1.0           r36h6115d3f_1002    conda-forge
r-class                   7.3_15          r36hcdcec82_1001    conda-forge
r-cli                     1.1.0             r36h6115d3f_2    conda-forge
r-clipr                   0.7.0             r36h6115d3f_0    conda-forge
r-clisymbols              1.2.0           r36h6115d3f_1002    conda-forge
r-codetools               0.2_16          r36h6115d3f_1001    conda-forge
r-colorspace              1.4_1             r36hcdcec82_1    conda-forge
r-commonmark              1.7             r36hcdcec82_1001    conda-forge
r-config                  0.3             r36h6115d3f_1002    conda-forge
r-crayon                  1.3.4           r36h6115d3f_1002    conda-forge
r-curl                    4.2               r36hcdcec82_0    conda-forge
r-data.table              1.12.6            r36hcdcec82_0    conda-forge
r-dbi                     1.0.0           r36h6115d3f_1002    conda-forge
r-dbplyr                  1.4.2             r36h6115d3f_1    conda-forge
r-desc                    1.2.0           r36h6115d3f_1002    conda-forge
r-devtools                2.1.0             r36h6115d3f_1    conda-forge
r-digest                  0.6.23            r36h0357c0b_0    conda-forge
r-dplyr                   0.8.3             r36h0357c0b_3    conda-forge
r-ellipsis                0.3.0             r36hcdcec82_0    conda-forge
r-evaluate                0.14              r36h6115d3f_1    conda-forge
r-fansi                   0.4.0           r36hcdcec82_1001    conda-forge
r-farver                  2.0.1             r36h0357c0b_0    conda-forge
r-forcats                 0.4.0             r36h6115d3f_1    conda-forge
r-foreach                 1.4.7             r36h6115d3f_0    conda-forge
r-forecast                8.7               r36h0357c0b_1    conda-forge
r-forge                   0.2.0             r36h6115d3f_1    conda-forge
r-fracdiff                1.4_2           r36hcdcec82_1003    conda-forge
r-fs                      1.3.1             r36h0357c0b_1    conda-forge
r-generics                0.0.2           r36h6115d3f_1002    conda-forge
r-ggplot2                 3.2.1             r36h6115d3f_0    conda-forge
r-gh                      1.0.1           r36h6115d3f_1002    conda-forge
r-git2r                   0.26.1            r36h5ca76e2_1    conda-forge
r-glue                    1.3.1             r36hcdcec82_1    conda-forge
r-gower                   0.2.1             r36hcdcec82_1    conda-forge
r-gtable                  0.3.0             r36h6115d3f_2    conda-forge
r-haven                   2.2.0             r36hde08347_0    conda-forge
r-hexbin                  1.27.3            r36h9bbef5b_2    conda-forge
r-highr                   0.8               r36h6115d3f_1    conda-forge
r-hms                     0.5.2             r36h6115d3f_0    conda-forge
r-htmltools               0.3.6           r36he1b5a44_1003    conda-forge
r-htmlwidgets             1.3             r36h6115d3f_1001    conda-forge
r-httpuv                  1.5.2             r36h0357c0b_1    conda-forge
r-httr                    1.4.1             r36h6115d3f_1    conda-forge
r-ini                     0.3.1           r36h6115d3f_1002    conda-forge
r-ipred                   0.9_9             r36hcdcec82_1    conda-forge
r-irdisplay               0.7                    r36_1001    conda-forge
r-irkernel                1.0.2             r36h6115d3f_2    conda-forge
r-iterators               1.0.12            r36h6115d3f_0    conda-forge
r-jsonlite                1.6             r36hcdcec82_1001    conda-forge
r-kernsmooth              2.23_15         r36h9bbef5b_1004    conda-forge
r-knitr                   1.26              r36h6115d3f_0    conda-forge
r-labeling                0.3             r36h6115d3f_1002    conda-forge
r-later                   1.0.0             r36h0357c0b_0    conda-forge
r-lattice                 0.20_38         r36hcdcec82_1002    conda-forge
r-lava                    1.6.6             r36h6115d3f_0    conda-forge
r-lazyeval                0.2.2             r36hcdcec82_1    conda-forge
r-lifecycle               0.1.0             r36h6115d3f_0    conda-forge
r-lmtest                  0.9_37            r36h9bbef5b_2    conda-forge
r-lubridate               1.7.4           r36h0357c0b_1002    conda-forge
r-magrittr                1.5             r36h6115d3f_1002    conda-forge
r-markdown                1.1               r36hcdcec82_0    conda-forge
r-mass                    7.3_51.4          r36hcdcec82_1    conda-forge
r-matrix                  1.2_17            r36hcdcec82_1    conda-forge
r-memoise                 1.1.0           r36h6115d3f_1003    conda-forge
r-mgcv                    1.8_29            r36hcdcec82_0    conda-forge
r-mime                    0.7               r36hcdcec82_1    conda-forge
r-modelmetrics            1.2.2             r36h0357c0b_1    conda-forge
r-modelr                  0.1.5             r36h6115d3f_0    conda-forge
r-munsell                 0.5.0           r36h6115d3f_1002    conda-forge
r-nlme                    3.1_141           r36h9bbef5b_1    conda-forge
r-nnet                    7.3_12          r36hcdcec82_1003    conda-forge
r-numderiv                2016.8_1.1        r36h6115d3f_1    conda-forge
r-nycflights13            1.0.1             r36h6115d3f_0    conda-forge
r-openssl                 1.4.1             r36h9c8475f_0    conda-forge
r-pbdzmq                  0.3_3           r36h559a7a4_1002    conda-forge
r-pillar                  1.4.2             r36h6115d3f_2    conda-forge
r-pkgbuild                1.0.6             r36h6115d3f_0    conda-forge
r-pkgconfig               2.0.3             r36h6115d3f_0    conda-forge
r-pkgload                 1.0.2           r36h0357c0b_1001    conda-forge
r-plogr                   0.2.0           r36h6115d3f_1002    conda-forge
r-plyr                    1.8.4           r36h0357c0b_1003    conda-forge
r-praise                  1.0.0           r36h6115d3f_1003    conda-forge
r-prettyunits             1.0.2           r36h6115d3f_1002    conda-forge
r-processx                3.4.1             r36hcdcec82_0    conda-forge
r-prodlim                 2019.11.13        r36h0357c0b_0    conda-forge
r-progress                1.2.2             r36h6115d3f_1    conda-forge
r-promises                1.1.0             r36h0357c0b_0    conda-forge
r-ps                      1.3.0           r36hcdcec82_1001    conda-forge
r-purrr                   0.3.3             r36hcdcec82_0    conda-forge
r-quadprog                1.5_7             r36h9bbef5b_2    conda-forge
r-quantmod                0.4_15            r36h6115d3f_1    conda-forge
r-r2d3                    0.2.3           r36h6115d3f_1001    conda-forge
r-r6                      2.4.1             r36h6115d3f_0    conda-forge
r-randomforest            4.6_14          r36h9bbef5b_1002    conda-forge
r-rappdirs                0.3.1           r36hcdcec82_1003    conda-forge
r-rcmdcheck               1.3.3             r36h6115d3f_2    conda-forge
r-rcolorbrewer            1.1_2           r36h6115d3f_1002    conda-forge
r-rcpp                    1.0.3             r36h0357c0b_0    conda-forge
r-rcpparmadillo           0.9.800.1.0       r36h0357c0b_0    conda-forge
r-rcurl                   1.95_4.12         r36hcdcec82_1    conda-forge
r-readr                   1.3.1           r36h0357c0b_1002    conda-forge
r-readxl                  1.3.1             r36h0357c0b_2    conda-forge
r-recipes                 0.1.7             r36h6115d3f_0    conda-forge
r-rematch                 1.0.1           r36h6115d3f_1002    conda-forge
r-remotes                 2.1.0             r36h6115d3f_1    conda-forge
r-repr                    1.0.1             r36h6115d3f_1    conda-forge
r-reprex                  0.3.0             r36h6115d3f_1    conda-forge
r-reshape2                1.4.3           r36h0357c0b_1004    conda-forge
r-rlang                   0.4.2             r36hcdcec82_0    conda-forge
r-rmarkdown               1.14              r36h6115d3f_1    conda-forge
r-roxygen2                7.0.2             r36h0357c0b_0    conda-forge
r-rpart                   4.1_15            r36hcdcec82_1    conda-forge
r-rprojroot               1.3_2           r36h6115d3f_1002    conda-forge
r-rsqlite                 2.1.2             r36h0357c0b_1    conda-forge
r-rstudioapi              0.10              r36h6115d3f_2    conda-forge
r-rvest                   0.3.5             r36h6115d3f_0    conda-forge
r-scales                  1.1.0             r36h6115d3f_0    conda-forge
r-selectr                 0.4_1           r36h6115d3f_1001    conda-forge
r-sessioninfo             1.1.1           r36h6115d3f_1001    conda-forge
r-shiny                   1.3.2             r36h6115d3f_1    conda-forge
r-sourcetools             0.1.7           r36he1b5a44_1001    conda-forge
r-sparklyr                1.0.5             r36h6115d3f_0    conda-forge
r-squarem                 2017.10_1       r36h6115d3f_1002    conda-forge
r-stringi                 1.4.3             r36h0357c0b_2    conda-forge
r-stringr                 1.4.0             r36h6115d3f_1    conda-forge
r-survival                2.44_1.1          r36hcdcec82_1    conda-forge
r-sys                     3.3               r36hcdcec82_0    conda-forge
r-testthat                2.3.1             r36h0357c0b_0    conda-forge
r-tibble                  2.1.3             r36hcdcec82_1    conda-forge
r-tidyr                   1.0.0             r36h0357c0b_0    conda-forge
r-tidyselect              0.2.5           r36h0357c0b_1001    conda-forge
r-tidyverse               1.2.1           r36h6115d3f_1002    conda-forge
r-timedate                3043.102        r36h6115d3f_1001    conda-forge
r-tinytex                 0.17              r36h6115d3f_0    conda-forge
r-tseries                 0.10_47           r36h9bbef5b_2    conda-forge
r-ttr                     0.23_5            r36hcdcec82_0    conda-forge
r-urca                    1.3_0           r36h9bbef5b_1004    conda-forge
r-usethis                 1.5.1             r36h6115d3f_1    conda-forge
r-utf8                    1.1.4           r36hcdcec82_1001    conda-forge
r-uuid                    0.1_2           r36hcdcec82_1002    conda-forge
r-vctrs                   0.2.0             r36hcdcec82_1    conda-forge
r-viridislite             0.3.0           r36h6115d3f_1002    conda-forge
r-whisker                 0.4               r36h6115d3f_0    conda-forge
r-withr                   2.1.2           r36h6115d3f_1001    conda-forge
r-xfun                    0.11              r36h6115d3f_0    conda-forge
r-xml2                    1.2.2             r36h0357c0b_0    conda-forge
r-xopen                   1.0.0           r36h6115d3f_1002    conda-forge
r-xtable                  1.8_4             r36h6115d3f_2    conda-forge
r-xts                     0.11_2            r36hcdcec82_1    conda-forge
r-yaml                    2.2.0           r36hcdcec82_1002    conda-forge
r-zeallot                 0.1.0           r36h6115d3f_1001    conda-forge
r-zoo                     1.8_6             r36hcdcec82_1    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rpy2                      2.9.4           py37r36h481b005_0    defaults
ruamel_yaml               0.15.80         py37h516909a_1000    conda-forge
scikit-image              0.15.0           py37hb3f55d8_2    conda-forge
scikit-learn              0.21.3           py37hcdab131_0    conda-forge
scipy                     1.3.2            py37h921218d_0    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.2                   py37_0    conda-forge
six                       1.13.0                   py37_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.4                    py37_0    conda-forge
sqlalchemy                1.3.11           py37h516909a_0    conda-forge
sqlite                    3.30.1               h7b6447c_0    defaults
statsmodels               0.10.2           py37hc1659b7_0    conda-forge
sympy                     1.4                      py37_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tini                      0.18.0            h14c3975_1001    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tktable                   2.10                 h555a92e_3    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.40.0                     py_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                he1b5a44_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge`

**Comment by scivm** [comment]
Issue is related to azurefile CIFS filesystem.  Jupyter core has been updated in 4.6.1 to allow execute on owner.  I am trying now trying to fix change group and world kubernetes pod definition built from kubespawner in jupyterhub.

https://github.com/jupyter/jupyter_core/issues/172

**Comment by kevin-bates** [comment]
Because you're using `jupyter_client == 5.3.3` it will not use the `secure_write` method that was moved to `jupyter_core == 4.6.1` and (as of 4.6.1) tolerates the execute bit.

I believe @MSeal is right about there being a conda-forge issue and it looks like @bollwyvl is [on the case](https://github.com/conda-forge/jupyter_client-feedstock/pull/36) - thank you!

**Pull request merged**
