### PR TITLE
Test downstream projects

### LINKED ISSUE #639: CI workflow to test downstream projects
It would be nice to have a workflow running on CI to test potential breaking changes with downstream projects like `jupyter_server` and others.

Which could be similar to the one used by `traitlets`:

https://github.com/ipython/traitlets/blob/master/.github/workflows/downstream.yml

### PR DESCRIPTION
**Pull request by davidbrochart**
Fixes #639

### CODE REVIEW

**Comment by blink1073** [comment]
Kicking CI

**Comment by blink1073** [comment]
Looks like still have some failures.  @davidbrochart are you able to pick this back up for the 7.0 release?

**Comment by davidbrochart** [comment]
Sure, I'm going to look into it.

**Comment by davidbrochart** [comment]
I commented out the tests for the following packages:
- `qtconsole`: core dump
- `jupyter_server`: pip package doesn't allow for testing (see https://github.com/jupyter-server/jupyter_server/issues/563)

We successfully pass the tests for:
- `ipykernel==6.0.3`
- `nbclient==0.5.3`
- `nbconvert==6.1.0`

**Review by blink1073 — APPROVED** [review]
Thank you!

**Comment by davidbrochart** [comment]
I just tested jupyter_server master locally with jupyter_client master and all tests pass except for one related with nbconvert, so I thinks we are fine on the jupyter_server side.
I opened https://github.com/jupyter/qtconsole/pull/494 and this should make qtconsole ready for jupyter_client 7.0.

**Pull request merged**
