### PR TITLE
Subprocess kill is not async

### PR DESCRIPTION
**Pull request by davidbrochart**
The issue was revealed in https://github.com/jupyter/nbclient/pull/37 and https://github.com/jupyter/jupyter_server/pull/191.

### CODE REVIEW

**Comment by MSeal** [comment]
Do we need a patch release to get the change available for those other PRs?

**Comment by kevin-bates** [comment]
I think this would be good as the jupyter_server PR produces intermittent failures during CI. I don't know about the nbclient behavior.

**Comment by MSeal** [comment]
This could explain some hanging tests we see in python 3.5 for nbclient, I'll kick off a release now

**Comment by MSeal** [comment]
6.1.1 is released

**Comment by kevin-bates** [comment]
Thank you.  I started drilling into the odd CI failure we've been seeing in the Notebook repo since about a month ago, and believe it is associated with JC 6.0.  The tests are failing in kernel.js for its auto-restart test.  

This theory is based on taking two of the failing PRs - of completely unrelated areas - and pinning their JC versions to 5.3.4 and both succeed.  Because 6.0 consists of numerous fixes from the master branch - some 2 years old - this might be difficult, but I'm going to focus on some of the PRs I added since they could be related to restarts in some manner (as most of my PRs are in the areas of kernel management).

At any rate, we might need a 6.1.2 sometime in the near future.

**Comment by MSeal** [comment]
Sounds great thanks for digging into it. I was going to start candidate testing 6.0 here but the virus has prompted delaying new changes for a couple weeks on our stacks.

**Comment by kevin-bates** [comment]
PR #536 has been submitted to address the NB CI failures.

**Pull request merged**
