### PR TITLE
fix kernel can only restart once issue

### PR DESCRIPTION
**Pull request by mofanke**
fix kernel can only resstart once  issue
fix issue https://github.com/jupyter/jupyter_client/issues/689

### CODE REVIEW

**Review by kevin-bates — COMMENTED** [review]
Hi @mofanke - thank you for the pull request.  I was thinking the reset would occur at the start of the start_kernel() method (rather than its post-start).  Did you try that and was it problematic?

**Comment by mofanke** [comment]
Hi, @kevin-bates  I have tried the reset in start_kernel(), pre_start_kernel() and post_start_kernel() , all the three ways can git rid of the problem.    "self.shutting_down = True"  setted in _async_shutdown_kernel()  just before "self.stop_restarter()" so I put "self.shutting_down = False"  as the reset just before "self.start_restarter()" in _async_post_start_kernel(). 

shoud I update the PR , and set "self.shutting_down = False"  in start_kernel()?

**Comment by kevin-bates** [comment]
Hi @mofanke - thanks for looking into the various solutions.  In looking at the history of `self.shuttting_down` I must have inadvertently removed its reset to `False` when introducing kernel provisioners.  It was previously located at the [start of `pre_start_kernel()`](https://github.com/jupyter/jupyter_client/commit/4d62c5b3733e8c4d54ceba743fb11e13f3c56ffc#diff-a3ba5852c735811a3643b5461c200d95819fe806dba20d1e4e692ecdba5cb62cR251), which makes the most sense to me since, at that point, it's no longer shutting down.  As such, I think its best to place it in that same relative location.  Thank you.

**Review by kevin-bates — APPROVED** [review]
LGTM - thank you @mofanke!

**Pull request merged**
