### PR TITLE
Make cache_ports configurable with default value of False.

### PR DESCRIPTION
**Pull request by jkitchin**
This addresses issue #878 and #955. Suggested by @kevin-bates.

### CODE REVIEW

**Comment by jkitchin** [comment]
I guess I should have added a label. I don't know what this would be considered, I guess an enhancment?

**Comment by kevin-bates** [comment]
>  I don't know what this would be considered, I guess an enhancement?

Given the previous discussion a while ago, I view this change as something that should have been part of the original change and have applied the `bug` label.

**Review by kevin-bates — APPROVED** [review]
LGTM - thank you @jkitchin

**Comment by jkitchin** [comment]
Does anything else need to happen to this?

**Comment by kevin-bates** [comment]
We usually give folks a day or two to review.  However, the build issue is also unwarranted but I believe it is probably unrelated.

@blink1073 - is the coverage issue due to some external version update or something like that?  (Sorry, I haven't been "close" to the repos lately.)

**Comment by blink1073** [comment]
The coverage thing is a weird artifact from switching away from codecov where it seems like coverage isn't honoring `relative_files = true` in some cases.  I've seen this on `nbconvert` as well.

**Comment by blink1073** [comment]
I'll cut a new release early next week.

**Comment by kevin-bates** [comment]
Thank you Steve!

**Pull request merged**
