### PR TITLE
Add local-provisioner entry point to pyproject.toml Fixes #800

### LINKED ISSUE #800: Kernel Provisioning: The 'local-provisioner' is not found.
I'm encountering a problem after the update to jupyter_client 7.3.2. The following error is appearing:

```
[W 2022-06-06 17:10:09.080 ServerApp] Kernel Provisioning: The 'local-provisioner' is not found.  This is likely due to the presence of multiple jupyter_client distributions and a previous distribution is being used as the source for entrypoints - which does not include 'local-provisioner'.  That distribution should be removed such that only the version-appropriate distribution remains (version >= 7).  Until then, a 'local-provisioner' entrypoint will be automatically constructed and used.
    The candidate distribution locations are: ['/home/jupyter/venv/lib/python3.10/site-packages/jupyter_client-7.3.2.dist-info']
```

I found a thread with a similar problem from last year:
https://discourse.jupyter.org/t/kernel-python-3-is-referencing-a-kernel-provisioner-local-provisioner-that-is-not-available-ensure-the-appropriate-package-has-been-installed-and-retry/10436/9

`pip install --force-reinstall jupyter_client` didn't help. Also, I've looked in `{sys.prefix}/lib/pythonX.Y/site-packaes` as was recommended, but I don't see a second directory.

I will probably delete the virtual environment and reinstall the whole jupyter instance from `pip install jupyter` to see if that fixes it.

### PR DESCRIPTION
**Pull request by utkonos**

### CODE REVIEW

**Review by kevin-bates — APPROVED** [review]
LGTM - thank you @utkonos for letting us know about and fixing the issue!

**Comment by kevin-bates** [comment]
@davidbrochart - since 7.3.2 is still fresh, would it be possible to easily crank out a 7.3.3 release to get this change?  Although the local provisioner still works in 7.3.2, it will always produce the warning message that something is not right.

If you're unable, I can spend time cutting 7.3.3 tomorrow (just have to dust off the cobwebs :smile: ) - so no worries.

**Comment by davidbrochart** [comment]
Sure, I released v7.3.3.

**Comment by kevin-bates** [comment]
Thank you @davidbrochart - your cutting the release is very much appreciated!

**Pull request merged**
