### PR TITLE
adapt KernelManager._kernel_spec_manager_changed to observe

### LINKED ISSUE #386: Session._key_changed is deprecated in traitlets 4.1
Getting a `DeprecationWarning` in `jupyter_client`, which appears to be issued by `traitlets`. Points to [this line]( https://github.com/jupyter/jupyter_client/blob/5.2.3/jupyter_client/session.py#L371 ) as problematic. Warning included below.

```python
/opt/conda3/lib/python3.6/site-packages/jupyter_client/session.py:371: DeprecationWarning: Session._key_changed is deprecated in traitlets 4.1: use @observe and @unobserve instead.
  def _key_changed(self):
```

### PR DESCRIPTION
**Pull request by rgbkrk**
Closes #386

### CODE REVIEW

**Review by kevin-bates — APPROVED** [review]
Thanks Kyle.  The attention to B/C for subclasses is appreciated.

**Comment by kevin-bates** [comment]
Hi @rgbkrk - I'm trying to test out #592 with https://github.com/jupyter/notebook/pull/5904 and running into the following...
```
[E 11:46:34.512 NotebookApp] Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
        type=mtype))
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 177, in start_kernel
        kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 184, in start_kernel
        km, kernel_name, kernel_id = self.pre_start_kernel(kernel_name, kwargs)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 172, in pre_start_kernel
        **constructor_kwargs
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 83, in create_kernel_manager
        km = kernel_manager_ctor(*args, **kwargs)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/traitlets/config/configurable.py", line 82, in __init__
        super(Configurable, self).__init__(**kwargs)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/traitlets/traitlets.py", line 1080, in __init__
        super_kwargs[key] = value
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/contextlib.py", line 119, in __exit__
        next(self.gen)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/traitlets/traitlets.py", line 1214, in hold_trait_notifications
        self.notify_change(change)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/traitlets/traitlets.py", line 1227, in notify_change
        return self._notify_observers(change)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/traitlets/traitlets.py", line 1264, in _notify_observers
        c(event)
      File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/traitlets/traitlets.py", line 888, in compatible_observer
        return func(self, change)
    TypeError: _kernel_spec_manager_changed() takes 1 positional argument but 2 were given
```
Does `_kernel_spec_manager_changed()` need a `changed` parameter added?  I'm seeing this issue with traitlets 4.3.3 and 5.0.5.  My guess is that this parameter was needed all along but its presence (or lack of) only comes into play with the `@observe_compat` decorator.

**Comment by takluyver** [comment]
I think this didn't quite avoid an issue - the method is missing the `change` parameter that `@observe_compat` expects.

**Comment by takluyver** [comment]
#598 is the change I think is needed to fix it

**Pull request merged**
