### PR TITLE
#268: README on setting up the development environment

### PR DESCRIPTION
**Pull request by rolweber**
see #268

### CODE REVIEW

**Comment by rolweber** [comment]
Just noticed that both `pytest` and `py.test` work, so the last commit was superfluous. But since both comments in the issue used the spelling with dot, I assume that is the preferred one.

**Comment by takluyver** [comment]
Thanks for opening this :-)

I think it's worth having some brief notes about how to run the tests and things, but I'm a bit concerned about putting this much information there. Most of this info is essentially the same for all our repos, and for many other Python packages out there, so we could end up with it duplicated in a lot of places, and duplicated content is at risk of getting out-of-date when things change.

Maybe we could simplify this to a couple of brief notes on how to do a development install and run the tests, and link to the [Jupyter contributor information](http://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html) for more details. Those docs may have room for improvement as well, but at least they're just in one [place](https://github.com/jupyter/jupyter/tree/master/docs/source).

**Comment by rolweber** [comment]
I basically collected the handful of commands that I expect to need on a regular basis, then put in some prose and external links to make it more readable. If I have to study the general developer documentation first to filter out duplicate information, that's gonna take a few days. Our README should definitely have pointers there, I agree.

Looking at the documentation part of [Getting Started](http://jupyter.readthedocs.io/en/latest/contrib_docs/getting-started.html#edit-the-documentation-source-file)...
- "Source files for projects are typically found in the project’s docs/source directory."  
  * Jupyter Client has them in `docs` rather than `docs/source`. We need to mention that.
- "In addition, you may need the following packages: sphinxcontrib-spelling, sphinx_rtd_theme, nbsphinx, pyenchant, recommonmark and jupyter_sphinx_theme, which can be installed via `pip install sphinxcontrib-spelling sphinx_rtd_theme nbsphinx pyenchant recommonmark jupyter_sphinx_theme`."  
  "If you are on Linux, you may also need to install the Enchant C library by running `sudo apt-get install enchant`."
  * Do you expect a beginner to even _try_ after reading this? I gave up way before `sudo`.

I recommend to put the frequently needed commands directly into the README for copy&paste, and add pointers to more extensive documentation for those willing to take the next steps. That should keep the learning curve smooth.

I'll take another stab at it later this week.

**Comment by rolweber** [comment]
I've trimmed down the prose and added relevant links to the Jupyter Guides. Please have another look.

**Comment by Carreau** [comment]
Thanks a lot, that's a big improvement. If we want to do better we can still refine that in subsequent PRs.

**Pull request merged**
