### PR TITLE
make fork-safety check optional

### PR DESCRIPTION
**Pull request by minrk**
allows other code to take over fork-safety, as is planned in ipython/ipykernel#85

### CODE REVIEW

**Comment by Carreau** [comment]
unfortunately need rebase.

**Comment by minrk** [comment]
rebased

**Comment by minrk** [comment]
Perhaps what makes more sense is a per-socket fork-safe signaling mechanism (e.g. `getattr(socket, '_fork_safe', False)`). Or we could assume objects that aren't zmq.Socket are fork-safe. I'm not sure what the best solution is.

**Comment by Carreau** [comment]
> Perhaps what makes more sense is a per-socket fork-safe signaling mechanism (e.g. getattr(socket, '_fork_safe', False)). Or we could assume objects that aren't zmq.Socket are fork-safe. I'm not sure what the best solution is.

Let's go with this one for now.

**Pull request merged**
