### PR TITLE
Remove deprecated zmq imports

### PR DESCRIPTION
**Pull request by blink1073**
closes #842

### CODE REVIEW

**Comment by blink1073** [comment]
Hmm, it appears we might have other problems with pyzmq 25.

**Comment by minrk** [comment]
I'll look into this now! I wouldn't expect issues with this very small release, but nobody ever _expects_ issues.

**Comment by minrk** [comment]
After isolating pyzmq, it seems this is related to pyqt5 integration changes, and not related to pyzmq at all.

**Comment by blink1073** [comment]
Okay, we do have to fix one test to not pass an asyncio socket to `ZMQStream`, but you're right it looks like the underlying issue is in `ipykernel`.

**Comment by blink1073** [comment]
Aha!  The problem is that we were explicitly installing `pyqt5` in our downstream `ipykernel` tests (here and in 7.x), which now requires a display buffer for testing.

**Pull request merged**
