### PR TITLE
Force install jupyter_client master

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
As pointed out by @blink1073, we didn't test jupyter_client master but whatever version was installed by the downstream packages.
With this PR we do and we can see that:
- ipykernel still uses `get_msg(block=...)`. I opened https://github.com/ipython/ipykernel/pull/736 to get rid of the `block` parameter.
- nbclient still uses `km.cleanup`. I opened https://github.com/jupyter/nbclient/pull/152 to replace it with `km.cleanup_resources`.

**Comment by blink1073** [comment]
Kicking CI

**Comment by davidbrochart** [comment]
nbclient has not been released so we're not testing it with https://github.com/jupyter/nbclient/pull/152.

**Comment by blink1073** [comment]
We can kick this again after upcoming releases of `ipykernel` and `nbclient` on Monday.

**Comment by blink1073** [comment]
Looka like we're still failing one test in `nbclient`

**Comment by blink1073** [comment]
Builds are passing in [nbclient](https://github.com/jupyter/nbclient/actions/runs/1134904828)

**Comment by davidbrochart** [comment]
Looks like we also have all the downstream packages' dependencies pre-release installed, in particular `ipywidgets==8.0.0a5` makes the nbclient test fail.

**Comment by davidbrochart** [comment]
I think this is the normal behavior of the `--pre` option. Maybe then we should install master versions of downstream packages (without `--pre`).

**Comment by blink1073** [comment]
Thank you!

**Pull request merged**
