### PR TITLE
update intersphinx target

### LINKED ISSUE #295: IPython execution semantics links to old ipython docs
For some reason, the "See also Execution semantics in the IPython kernel" note at the end of http://jupyter-client.readthedocs.io/en/latest/messaging.html#execute links to the old IPython docs on ipython.org, rather than the RTD ipython docs.

### PR DESCRIPTION
**Pull request by willingc**
Closes #295 

Rendering of updated version on my test system: http://test-jupclient.readthedocs.io/en/execution/messaging.html#execute

### CODE REVIEW

**Comment by willingc** [comment]
cc/ @jzf2101

**Comment by willingc** [comment]
@jzf2101 There are a few other repos that need to be updated in the same manner. Here are the search results across the orgs:

https://github.com/search?l=&q=intersphinx+ipython+user%3Ajupyter+user%3Ajupyterhub+user%3Aipython+user%3Ajupyterlab+user%3Ajupyter-widgets&ref=advsearch&type=Code&utf8=✓

**Comment by Carreau** [comment]
@willingc Do you have a new avatar ? It look nice !

**Comment by willingc** [comment]
@Carreau I do. Thanks! It's from JupyterCon. The larger photo has the Rubik's cube in my hands. Remember the cubes?

**Comment by Carreau** [comment]
> It's from JupyterCon. 

That's what I thought

> The larger photo has the Rubik's cube in my hands. Remember the cubes?

Nice, yes I do remember the cube, I still have mine !

Let's get that in ! Thanks !

**Comment by Carreau** [comment]
Note (I've send similar PR to matplotlib and dask)

**Comment by rgbkrk** [comment]
Thank you! I was having some serious trouble trying to figure this one out.

**Pull request merged**
