### PR TITLE
import sys because it is used.

### PR DESCRIPTION
**Pull request by Carreau**
The foloowing line for example:

> print("ipython_kernel not available, can't install its spec.", file=sys.stderr)

### CODE REVIEW

**Comment by ivanov** [comment]
LGTM!

**Comment by Carreau** [comment]
Hey @ivanov ! what are you doing here ! we miss you !

**Comment by ivanov** [comment]
:heart:

**Comment by Carreau** [comment]
:kiss: !

**Comment by ivanov** [comment]
:dancer:

**Comment by rgbkrk** [comment]
:cake:

**Comment by minrk** [comment]
:fish_cake:

**Pull request merged**
