### PR TITLE
Clean changelog heading

### PR DESCRIPTION
**Pull request by krassowski**
I think this may not be required, but apologies if it is. This currently renders as-is in the docs:

Screenshot from 2023-08-31 20-50-21

I believe jupyter-releaser uses `<!-- <START NEW CHANGELOG ENTRY> -->` markers, so I am not sure why this was included/retained.

### CODE REVIEW

**Comment by krassowski** [comment]
@blink1073 I assume you are the maintainer in question ;) Would it help if the bot was allowed to label?

**Comment by krassowski** [comment]
Anyone with rights to review?

**Review by davidbrochart — APPROVED** [review]
LGTM, thanks @krassowski.

**Comment by davidbrochart** [comment]
But it looks I cannot merge :disappointed:

**Comment by krassowski** [comment]
Thanks @Carreau for the merge and updating rights for me and @davidbrochart!

**Pull request merged**
