### PR TITLE
Backport of master to 5.x

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@davidbrochart I will hit merge if you can drop afbb34a4fe0339c595bcab7260970ca45ff7f80a

**Comment by SylvainCorlay** [comment]
(master is 6.0-dev)

**Comment by MSeal** [comment]
Also thanks a ton @davidbrochart for helping make all these PRs and drive getting async released across projects. Really appreciate the contributions!

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay do you agree? Or would you rather we keep 5.x pure and do a version change in master only. Or do you strongly think we should stay as 5.x?

sounds good to me

**Comment by SylvainCorlay** [comment]
@MSeal @minrk @davidbrochart 

As discussed, I have created a new "kernel_discovery" branch with the content of master and reset master to 5.x. There is no 5.x branch anymore.

Most PRs to master will need to be rebased, although a lot of them are very outdated and should probably be closed.

**Comment by MSeal** [comment]
Agreed and thanks for doing that, we should do some house cleaning anyway on those old PRs. I can get a release going this weekend unless downstream testing hits an issue. I will want to do some testing in the more common downstream libraries and apply python 3 only changes to the setup / release docs.

**Comment by MSeal** [comment]
Continuing the conversation in https://github.com/jupyter/jupyter_client/issues/511

**Pull request merged**
