### PR TITLE
match pep 440 version scheme

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by minrk** [comment]
I'm :-1: on that, actually.

**Comment by Carreau** [comment]
Any reason why ? Seem like following a standard might be a good thing...

**Comment by minrk** [comment]
If we are doing it properly, we should be revving the number on every build / install, not just using 0 all the time. This part of PEP 440 bugs me a lot, actually. I think it was a mistake.

**Comment by minrk** [comment]
Also, I assume you are doing this because of the message from pip 6:

> UserWarning: The version specified requires normalization, consider using '4.0.0.dev0' instead of '4.0.0-dev'.

They realized this message was a bad idea, and no longer show it in pip 7.

**Comment by Carreau** [comment]
Ok,fair enough. I still feel sad that we don't match the pep. I'm not sure where in the pep is stated that we should update the N on each build. I see that more as a number if we had nightly build

**Pull request closed without merging**
