### PR TITLE
Add kernel spec name to connection file

### LINKED ISSUE #50: Include kernelspec name in connection file
For frontends like [sidecar](https://github.com/rgbkrk/jupyter-sidecar), it would be nice if connection files included the kernelspec name. This is solely to find out the logo and language name without having to make a `kernel_info_request`.

/cc @minrk @jdfreder from discussions at Medici Cafe in Austin

### PR DESCRIPTION
**Pull request by captainsafia**
Closes #50.

This doesn't feel like the right approach so opening up this PR for advisement.

cc/ @minrk

### CODE REVIEW

**Comment by minrk** [comment]
What doesn't feel right about this?

**Comment by captainsafia** [comment]
I'm not entirely sure that the `kernel_name` is propagated properly when the connection file is loaded. For example, if in the test case I sent the `kernel_name` key in the `sample_info` to a value other than "Python" then the test for `load_connection_file` still returns "python" instead of "test" which makes me think that perhaps that `load_connection_file` overwrites the `kernel_name` variable somewhere.

Let me know if some of that doesn't make sense. I'll also push the test set I've been using.

**Comment by rgbkrk** [comment]
Looks like you've updated it. How are you feeling about it @minrk?

**Comment by minrk** [comment]
AOK :+1:

**Comment by rgbkrk** [comment]
Thanks @captainsafia!

**Pull request merged**
