### PR TITLE
Add block=True back to get_msg()

### PR DESCRIPTION
**Pull request by davidbrochart**
See https://github.com/jupyter/jupyter_client/issues/640#issue-856223866

### CODE REVIEW

**Comment by kevin-bates** [comment]
I was going to comment on whether or not we should deprecate the `block` parameter at this time (and remove it in 7.0) and/or document that `timeout` is only used when `block == True` (although the comment was the same previously).   Kind of an odd API and agree that the `timeout` value serves that purpose just fine.  We should probably default its value to `0` once `block` is removed (IMO).

**Comment by davidbrochart** [comment]
Ah, sorry for merging so quickly. Actually, now that we decided to go for a major release and it's still a pre-release, we could remove it.
But defaulting `timeout` to `0` means we just poll for a message, which is the opposite of what we have now by default (we wait until we have a message)?

**Comment by kevin-bates** [comment]
> But defaulting timeout to 0 means we just poll for a message, which is the opposite of what we have now by default (we wait until we have a message)?

I see.  I haven't looked at the socket poll() method, but now see what you're saying where `None` essentially means wait until we have a message.  Yeah, that should probably remain the default then.

**Comment by davidbrochart** [comment]
I think we can get rid of the `block` parameter, since we can do anything with `timeout` only. I opened #671.

**Pull request merged**
