### PR TITLE
Protect `popen`

### LINKED ISSUE #98: Inscrutable error with bad kernelspec file
Having updated my python installation I had old and invalid kernelspec files lying around which prevented the notebook from starting a kernel. The error message which was thrown was `OSError: [WinError 193] %1 is not a valid Win32 application` which is pretty uninformative. To debug I had to manually patch `launcher.py` to  show the cmd which failed to run.
```python
[E 08:00:07.343 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\bin\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 109, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\bin\Anaconda3\lib\subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "C:\bin\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
        startupinfo)
    OSError: [WinError 193] %1 is not a valid Win32 application
```

### PR DESCRIPTION
**Pull request by dhirschfeld**
Fixes #98

### CODE REVIEW

**Comment by dhirschfeld** [comment]
I'm not overly happy  with the `print` statement, but I'm not sure how to do something which is both python2 and python3 compatible

 On python3 I would use `raise from` but that's not available on python2. Conversely on python2 I would use `raise exc_type, exc_type(msg), tb` but that's invalid syntax on python3. So in the end I just went with print which does the job of providing some context to the error.

**Comment by dhirschfeld** [comment]
After this PR:
```
[I 08:33:05.288 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Failed to run command:
['C:\\DOESNOTEXIST\\Anaconda3\\python.exe', '-m', 'ipykernel', '-f', 'C:\\Users\\Dave\\AppData\\Roaming\\jupyter\\runtime\\kernel-73b0724d-16b8-4beb-89f5-58c91b0686a9.json']
with kwargs:
{'stdout': None, 'stderr': None, 'env': {<snip>}, 'cwd': 'C:\\Users\\Dave\\Code\\sandbox\\notebooks', 'stdin': -1}

[E 08:33:25.950 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\bin\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 436, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\bin\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 56, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "C:\bin\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "C:\bin\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 84, in start_kernel
        **kwargs)
      File "C:\bin\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 109, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\bin\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 244, in start_kernel
        **kw)
      File "C:\bin\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 190, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\bin\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 119, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\bin\Anaconda3\lib\subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "C:\bin\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by takluyver** [comment]
I think this broadlyis broadly correct, but I would use the logging framework to display the details rather than just printing:

```python
from traitlets.log import get_logger
get_logger().error(msg)
```

**Comment by dhirschfeld** [comment]
Like that?

**Comment by minrk** [comment]
Precisely, yes. Thanks.

**Pull request merged**
