### PR TITLE
Make Qtconsole work with PyZMQ 25

### PR DESCRIPTION
**Pull request by ccordoba12**
- It seems PyZMQ streams return now a list of bytes and not a future, so this was not handled properly.
- This doesn't seem necessary on the `main` branch.

### CODE REVIEW

**Comment by ccordoba12** [comment]
I'm also seeing this warning printed in the terminal when Qtconsole starts:

```
/home/carlos/Projects/jupyter_client/jupyter_client/threaded.py:73: RuntimeWarning: ZMQStream only supports the base zmq.Socket class.

                Use zmq.Socket(shadow=other_socket)
                or `ctx.socket(zmq.DEALER, socket_class=zmq.Socket)`
                to create a base zmq.Socket object,
                no matter what other kind of socket your Context creates.
                
  self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
```

but I don't know how to fix it.

**Comment by ccordoba12** [comment]
Ok, I think this also requires #482 to make the tests pass. Pinging @blink1073 and @minrk about it.

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by ccordoba12** [comment]
Thanks @blink1073 for your help with this! It seems the ipykernel failure is caused by the new Qt eventloop integration, but I don't know how to fix it.

**Comment by minrk** [comment]
For tracking, the change is https://github.com/zeromq/pyzmq/pull/1785 which 'fixes' ZMQStream compatibility with async sockets (with a warning, because passing an async socket to ZMQStream indicates an odd mixture of async/sync APIs).

ZMQStream never supported wrapping async sockets before pyzmq 25, but instead of raising it would fire callbacks with the wrong type (usually a Future instead of the message). Now, the `on_recv` callback will get the same arguments, no matter what socket class it's been called with.

The general fix that will work on all pyzmq versions is to ensure that ZMQStream is passed a regular zmq socket, which I believe was done in #835.

**Pull request merged**
